development:
  adapter: postgis
  encoding: unicode
  database: postgis_development<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  pool: 10
  username: postgres
  password: test
  postgis_extension: true
  schema_search_path: public,postgis
  port: 5432

test:
  adapter: postgis
  encoding: unicode
  database: postgis_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  pool: 10
  username: postgres
  password: test
  postgis_extension: true
  schema_search_path: public,postgis
  port: 5432
